modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="feur_shadow_elytra"
version="${file.jarVersion}"
displayName="Feur Shadow Elytra (Independent)"
authors="you"
description="Standalone Elytra items rendering internal wing textures without external dependencies."

[[dependencies.feur_shadow_elytra]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.feur_shadow_elytra]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
