name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle 8.8
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.8

      - name: Build
        run: gradle --no-daemon build
