name: Build

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle user home
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Gradle 8.8 (no wrapper)
        run: |
          set -e
          sudo apt-get update -y
          sudo apt-get install -y unzip curl
          curl -L -o gradle-8.8-bin.zip https://services.gradle.org/distributions/gradle-8.8-bin.zip
          unzip -q gradle-8.8-bin.zip
          echo "$PWD/gradle-8.8/bin" >> $GITHUB_PATH
          gradle --version

      - name: Build
        run: gradle --no-daemon build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: feur-shadow-elytra-jars
          path: build/libs/*.jar

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: feur-shadow-elytra-jars
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

